import type { Express, Request, Response } from "express";
import { createServer, type Server } from "http";
import { storage } from "./storage";
import { db, pool } from "./db";
import { z } from "zod";
import { 
  insertProductSchema, 
  insertSupplierSchema, 
  insertCategorySchema, 
  insertImportSchema,
  insertExportSchema,
  insertApprovalSchema,
  insertDataSourceSchema,
  insertMappingTemplateSchema,
  schedules,
  dataSources,
  categories,
  products,
  imports,
  exportsTable,
  approvals,
  mappingTemplates,
  suppliers
} from "@shared/schema";
import { eq, and, isNull } from "drizzle-orm";
import multer from "multer";
import path from "path";
import fs from "fs";
import { parse as parseCsv } from "csv-parse/sync";

// Import connections routes
import { registerConnectionsRoutes } from "./connections";

// Set up multer for file uploads
const upload = multer({
  storage: multer.diskStorage({
    destination: (req, file, cb) => {
      const uploadDir = path.resolve(process.cwd(), "uploads");
      if (!fs.existsSync(uploadDir)) {
        fs.mkdirSync(uploadDir, { recursive: true });
      }
      cb(null, uploadDir);
    },
    filename: (req, file, cb) => {
      cb(null, `${Date.now()}-${file.originalname}`);
    }
  }),
  limits: {
    fileSize: 10 * 1024 * 1024, // 10MB limit
  }
});

// Multi-Vendor Category Mapping Intelligence
async function createOrFindCategoryByPath(categoryPath: string): Promise<number> {
  if (!categoryPath || categoryPath.trim() === '') {
    // Create default "Uncategorized" if no path provided
    return await createOrFindCategoryByPath('Uncategorized');
  }

  // Parse hierarchical category like "Marine Navigation & Instruments | Compasses"
  const parts = categoryPath.split('|').map(part => part.trim());
  let parentId: number | null = null;
  let currentLevel = 0;
  let fullPath = '';

  for (const part of parts) {
    if (!part) continue;
    
    fullPath = fullPath ? `${fullPath} | ${part}` : part;
    
    // Check if category already exists at this level with this parent
    const existingQuery = parentId 
      ? and(eq(categories.name, part), eq(categories.parentId, parentId))
      : and(eq(categories.name, part), isNull(categories.parentId));
    
    const existing = await db.select().from(categories).where(existingQuery);

    if (existing.length > 0) {
      parentId = existing[0].id;
    } else {
      // Create new category with intelligent attributes based on industry
      const attributes = generateCategoryAttributes(part, fullPath, currentLevel);
      
      const newCategoryResult: any = await db.insert(categories).values({
        name: part,
        code: generateCategoryCode(part),
        parentId: parentId,
        level: currentLevel,
        path: fullPath,
        attributes: attributes
      }).returning();
      
      if (Array.isArray(newCategoryResult) && newCategoryResult.length > 0) {
        parentId = newCategoryResult[0].id;
      }
      
      console.log(`🏗️ Created new category: ${fullPath} (ID: ${parentId})`);
    }
    
    currentLevel++;
  }

  return parentId!;
}

// Generate category code from name
function generateCategoryCode(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9\s&]/g, '')
    .replace(/\s+/g, '-')
    .replace(/&/g, 'and')
    .substring(0, 50);
}

// Generate intelligent category attributes based on industry patterns
function generateCategoryAttributes(categoryName: string, fullPath: string, level: number): Record<string, any> {
  const attributes: Record<string, any> = {
    autoGenerated: true,
    level: level,
    industryHints: []
  };

  // Detect industry patterns and add relevant attributes
  const lowerName = categoryName.toLowerCase();
  const lowerPath = fullPath.toLowerCase();

  // Marine industry detection
  if (lowerPath.includes('marine') || lowerPath.includes('navigation') || 
      lowerPath.includes('compass') || lowerPath.includes('boat')) {
    attributes.industry = 'marine';
    attributes.industryHints.push('marine', 'outdoor', 'navigation');
    if (lowerName.includes('compass')) {
      attributes.specifications = ['accuracy', 'waterproof_rating', 'mounting_type'];
    }
  }
  
  // Electronics industry detection
  else if (lowerPath.includes('electronics') || lowerPath.includes('computer') || 
           lowerPath.includes('smartphone') || lowerPath.includes('tablet')) {
    attributes.industry = 'electronics';
    attributes.industryHints.push('technology', 'consumer_electronics', 'digital');
    attributes.specifications = ['warranty', 'compatibility', 'power_consumption'];
  }
  
  // Tools industry detection
  else if (lowerPath.includes('tools') || lowerPath.includes('hardware') || 
           lowerPath.includes('equipment')) {
    attributes.industry = 'tools';
    attributes.industryHints.push('industrial', 'construction', 'professional');
    attributes.specifications = ['power_type', 'material', 'durability_rating'];
  }

  // Add level-specific attributes
  if (level === 0) {
    attributes.isRootCategory = true;
    attributes.suggestedFilters = ['brand', 'price_range'];
  } else if (level >= 2) {
    attributes.isSpecificCategory = true;
    attributes.suggestedFilters = ['price_range', 'features', 'compatibility'];
  }

  return attributes;
}

// Helper function to format error responses
const handleError = (res: Response, error: any) => {
  console.error("API Error:", error);
  if (error instanceof z.ZodError) {
    return res.status(400).json({ 
      message: "Validation error", 
      errors: error.errors 
    });
  }
  return res.status(500).json({ message: error.message || "Internal server error" });
};

// Simulate Amazon search with confidence scoring
async function simulateAmazonSearch(productData: any, sampleAsins: string[], merchantId: string, marketplaceId: string) {
  const searchSequence = [];
  let confidenceScore = 0;
  let matchedCriteria = [];
  
  // UPC search (highest confidence)
  if (productData.upc) {
    searchSequence.push({
      method: 'upc_search',
      query: productData.upc,
      results: sampleAsins.length > 0 ? 1 : 0
    });
    if (sampleAsins.length > 0) {
      confidenceScore += 40;
      matchedCriteria.push('UPC Match');
    }
  }
  
  // MPN search (medium-high confidence)
  if (productData.manufacturerPartNumber) {
    searchSequence.push({
      method: 'mpn_search', 
      query: productData.manufacturerPartNumber,
      results: sampleAsins.length > 1 ? 1 : 0
    });
    if (sampleAsins.length > 1) {
      confidenceScore += 30;
      matchedCriteria.push('MPN Match');
    }
  }
  
  // Title search (medium confidence)
  if (productData.name) {
    searchSequence.push({
      method: 'title_search',
      query: productData.name,
      results: sampleAsins.length > 2 ? 1 : 0
    });
    if (sampleAsins.length > 2) {
      confidenceScore += 20;
      matchedCriteria.push('Title Match');
    }
  }
  
  const confidenceTier = confidenceScore >= 70 ? 'high' : 
                        confidenceScore >= 40 ? 'medium' : 'low';
  
  return {
    search_sequence: searchSequence,
    confidence_score: Math.min(100, confidenceScore),
    confidence_tier: confidenceTier,
    search_criteria: {
      upc: productData.upc,
      mpn: productData.manufacturerPartNumber,
      title: productData.name
    },
    matched_criteria: matchedCriteria
  };
}

export async function registerRoutes(app: Express): Promise<Server> {
  
  // Load route modules safely with error handling
  const loadRouteModule = async (modulePath: string, routeName: string) => {
    try {
      return await import(modulePath);
    } catch (error) {
      console.warn(`Failed to load ${routeName} routes from ${modulePath}:`, error);
      return null;
    }
  };

  // Suppliers API
  app.get("/api/suppliers", async (req, res) => {
    try {
      const suppliers = await storage.getSuppliers();
      res.json(suppliers);
    } catch (error) {
      handleError(res, error);
    }
  });

  app.get("/api/suppliers/:id", async (req, res) => {
    try {
      const supplier = await storage.getSupplier(Number(req.params.id));
      if (!supplier) {
        return res.status(404).json({ message: "Supplier not found" });
      }
      res.json(supplier);
    } catch (error) {
      handleError(res, error);
    }
  });

  app.post("/api/suppliers", async (req, res) => {
    try {
      const validatedData = insertSupplierSchema.parse(req.body);
      const supplier = await storage.createSupplier(validatedData);
      
      // Create audit log
      await storage.createAuditLog({
        action: "create",
        entityType: "supplier",
        entityId: supplier.id,
        details: { supplier }
      });
      
      res.status(201).json(supplier);
    } catch (error) {
      handleError(res, error);
    }
  });

  app.put("/api/suppliers/:id", async (req, res) => {
    try {
      const id = Number(req.params.id);
      const validatedData = insertSupplierSchema.partial().parse(req.body);
      const updatedSupplier = await storage.updateSupplier(id, validatedData);
      
      if (!updatedSupplier) {
        return res.status(404).json({ message: "Supplier not found" });
      }
      
      // Create audit log
      await storage.createAuditLog({
        action: "update",
        entityType: "supplier",
        entityId: id,
        details: { 
          before: await storage.getSupplier(id),
          after: updatedSupplier
        }
      });
      
      res.json(updatedSupplier);
    } catch (error) {
      handleError(res, error);
    }
  });

  // Categories API
  app.get("/api/categories", async (req, res) => {
    try {
      const categories = await storage.getCategories();
      res.json(categories);
    } catch (error) {
      handleError(res, error);
    }
  });

  app.get("/api/categories/:id", async (req, res) => {
    try {
      const id = parseInt(req.params.id);
      if (isNaN(id)) {
        return res.status(400).json({ message: "Invalid category ID" });
      }
      const category = await storage.getCategory(id);
      if (!category) {
        return res.status(404).json({ message: "Category not found" });
      }
      res.json(category);
    } catch (error) {
      handleError(res, error);
    }
  });

  app.post("/api/categories", async (req, res) => {
    try {
      const validatedData = insertCategorySchema.parse(req.body);
      const category = await storage.createCategory(validatedData);
      
      // Create audit log
      await storage.createAuditLog({
        action: "create",
        entityType: "category",
        entityId: category.id,
        details: { category }
      });
      
      res.status(201).json(category);
    } catch (error) {
      handleError(res, error);
    }
  });

  app.put("/api/categories/:id", async (req, res) => {
    try {
      const id = parseInt(req.params.id);
      if (isNaN(id)) {
        return res.status(400).json({ message: "Invalid category ID" });
      }
      const validatedData = insertCategorySchema.partial().parse(req.body);
      const updatedCategory = await storage.updateCategory(id, validatedData);
      
      if (!updatedCategory) {
        return res.status(404).json({ message: "Category not found" });
      }
      
      // Create audit log
      await storage.createAuditLog({
        action: "update",
        entityType: "category",
        entityId: id,
        details: { 
          before: await storage.getCategory(id),
          after: updatedCategory
        }
      });
      
      res.json(updatedCategory);
    } catch (error) {
      handleError(res, error);
    }
  });

  app.delete("/api/categories/:id", async (req, res) => {
    try {
      const id = parseInt(req.params.id);
      if (isNaN(id)) {
        return res.status(400).json({ message: "Invalid category ID" });
      }
      const success = await storage.deleteCategory(id);
      
      if (!success) {
        return res.status(404).json({ message: "Category not found" });
      }
      
      // Create audit log
      await storage.createAuditLog({
        action: "delete",
        entityType: "category",
        entityId: id,
        details: {}
      });
      
      res.json({ success: true });
    } catch (error) {
      handleError(res, error);
    }
  });

  // Category Mapping API
  app.get("/api/categories/mappings", async (req, res) => {
    try {
      const mappings = await storage.getCategoryMappings();
      res.json(mappings);
    } catch (error) {
      handleError(res, error);
    }
  });

  app.get("/api/categories/unmapped", async (req, res) => {
    try {
      const unmapped = await storage.getUnmappedSupplierCategories();
      res.json(unmapped);
    } catch (error) {
      handleError(res, error);
    }
  });

  app.post("/api/categories/mappings", async (req, res) => {
    try {
      const mappingData = req.body;
      const mapping = await storage.createCategoryMapping(mappingData);
      res.status(201).json(mapping);
    } catch (error) {
      handleError(res, error);
    }
  });

  app.put("/api/categories/mappings/:id", async (req, res) => {
    try {
      const id = parseInt(req.params.id);
      if (isNaN(id)) {
        return res.status(400).json({ message: "Invalid mapping ID" });
      }
      const mappingData = req.body;
      const updatedMapping = await storage.updateCategoryMapping(id, mappingData);
      res.json(updatedMapping);
    } catch (error) {
      handleError(res, error);
    }
  });

  // Products API
  app.get("/api/products", async (req, res) => {
    try {
      // Get products with ASIN mappings joined
      const productsQuery = `
        SELECT p.id, p.sku, p.usin, p.name, p.description,
               p.category_id as "categoryId",
               p.manufacturer_id as "manufacturerId", 
               p.manufacturer_name as "manufacturerName",
               p.manufacturer_part_number as "manufacturerPartNumber",
               p.upc, p.price, p.cost, p.weight, p.dimensions, p.attributes, p.status,
               p.is_remanufactured as "isRemanufactured",
               p.is_closeout as "isCloseout", 
               p.is_on_sale as "isOnSale",
               p.has_rebate as "hasRebate",
               p.has_free_shipping as "hasFreeShipping",
               p.inventory_quantity as "inventoryQuantity",
               p.reorder_threshold as "reorderThreshold",
               p.image_url as "imageUrl",
               p.image_url_large as "imageUrlLarge",
               p.third_party_marketplaces as "thirdPartyMarketplaces",
               p.case_quantity as "caseQuantity",
               p.google_merchant_category as "googleMerchantCategory",
               p.country_of_origin as "countryOfOrigin",
               p.box_height as "boxHeight",
               p.box_length as "boxLength", 
               p.box_width as "boxWidth",
               p.installation_guide_url as "installationGuideUrl",
               p.owners_manual_url as "ownersManualUrl",
               p.brochure_url as "brochureUrl",
               p.quick_guide_url as "quickGuideUrl",
               p.additional_images as "additionalImages",
               p.is_oversized as "isOversized",
               p.is_returnable as "isReturnable",
               p.quick_specs as "quickSpecs",
               p.next_shipment_date_nj as "nextShipmentDateNJ",
               p.next_shipment_date_fl as "nextShipmentDateFL",
               p.next_shipment_date_combined as "nextShipmentDateCombined",
               p.primary_image as "primaryImage",
               p.last_amazon_sync as "lastAmazonSync",
               p.amazon_sync_status as "amazonSyncStatus",
               p.created_at as "createdAt",
               p.updated_at as "updatedAt",
               c.name as "categoryName"
        FROM products p
        LEFT JOIN categories c ON p.category_id = c.id
        ORDER BY p.id
      `;
      
      const result = await pool.query(productsQuery);
      const products = result.rows;
      
      res.json(products);
    } catch (error) {
      handleError(res, error);
    }
  });

  // Basic CRUD operations for products
  app.get("/api/products/:id", async (req, res) => {
    try {
      const productId = parseInt(req.params.id);
      if (isNaN(productId)) {
        return res.status(400).json({ message: "Invalid product ID" });
      }
      
      const product = await storage.getProduct(productId);
      if (!product) {
        return res.status(404).json({ message: "Product not found" });
      }
      
      res.json(product);
    } catch (error) {
      handleError(res, error);
    }
  });

  app.post("/api/products", async (req, res) => {
    try {
      const validatedData = insertProductSchema.parse(req.body);
      const product = await storage.createProduct(validatedData);
      
      // Create audit log
      await storage.createAuditLog({
        action: "create",
        entityType: "product",
        entityId: product.id,
        details: { product }
      });
      
      res.status(201).json(product);
    } catch (error) {
      handleError(res, error);
    }
  });

  app.put("/api/products/:id", async (req, res) => {
    try {
      const id = Number(req.params.id);
      const validatedData = insertProductSchema.partial().parse(req.body);
      const updatedProduct = await storage.updateProduct(id, validatedData);
      
      if (!updatedProduct) {
        return res.status(404).json({ message: "Product not found" });
      }
      
      // Create audit log
      await storage.createAuditLog({
        action: "update",
        entityType: "product",
        entityId: id,
        details: { 
          before: await storage.getProduct(id),
          after: updatedProduct
        }
      });
      
      res.json(updatedProduct);
    } catch (error) {
      handleError(res, error);
    }
  });

  app.delete("/api/products/:id", async (req, res) => {
    try {
      const id = Number(req.params.id);
      const product = await storage.getProduct(id);
      
      if (!product) {
        return res.status(404).json({ message: "Product not found" });
      }
      
      const success = await storage.deleteProduct(id);
      
      if (success) {
        // Create audit log
        await storage.createAuditLog({
          action: "delete",
          entityType: "product",
          entityId: id,
          details: { product }
        });
      }
      
      res.json({ success });
    } catch (error) {
      handleError(res, error);
    }
  });

  // Statistics API
  app.get("/api/statistics", async (req, res) => {
    try {
      const products = await storage.getProducts();
      const suppliers = await storage.getSuppliers();
      const imports = await storage.getImports();
      const approvals = await storage.getApprovals();
      
      const pendingApprovals = approvals.filter(a => a.status === "pending").length;
      const successfulImports = imports.filter(i => i.status === "success").length;
      
      // Calculate data quality metrics (simulated)
      const dataQuality = {
        overall: 86,
        completeness: 91,
        consistency: 82,
        accuracy: 79,
        timeliness: 95
      };
      
      // Calculate pipeline performance (simulated)
      const pipelinePerformance = {
        ingestRate: "8.5K/hour",
        normalizationRate: "7.1K/hour",
        matchRate: "94.2%",
        autoApprovalRate: "78.5%",
        syncSuccessRate: "99.8%"
      };
      
      res.json({
        totalProducts: products.length,
        activeSuppliers: suppliers.filter(s => s.active).length,
        successfulImports30d: successfulImports,
        pendingApprovals: pendingApprovals,
        dataQuality,
        pipelinePerformance
      });
    } catch (error) {
      handleError(res, error);
    }
  });

  // Load optional route modules
  try {
    const marketplaceModule = await loadRouteModule("./marketplace/routes", "marketplace");
    if (marketplaceModule?.default) {
      app.use("/api/marketplace", marketplaceModule.default);
    }
  } catch (error) {
    console.warn("Marketplace routes not available:", error);
  }

  try {
    registerConnectionsRoutes(app);
  } catch (error) {
    console.warn("Connections routes not available:", error);
  }

  // Get sample data from data source (for field mapping)
  app.get("/api/datasources/:id/sample-data", async (req, res) => {
    try {
      const dataSourceId = parseInt(req.params.id);
      
      // Get data source details
      const [dataSource] = await db
        .select()
        .from(dataSources)
        .where(eq(dataSources.id, dataSourceId));
        
      if (!dataSource) {
        return res.status(404).json({ error: "Data source not found" });
      }
      
      // For demo purposes, read from a sample CSV file or use connections.ts logic
      // This would normally connect to the actual SFTP/FTP source
      const sampleCsvPath = path.resolve(process.cwd(), "catalog.csv");
      
      if (fs.existsSync(sampleCsvPath)) {
        const csvContent = fs.readFileSync(sampleCsvPath, 'utf-8');
        const records = parseCsv(csvContent, { 
          columns: true, 
          skip_empty_lines: true,
          delimiter: ','
        });
        
        // Return first 5 records for mapping
        res.json({ 
          success: true, 
          data: records.slice(0, 5),
          totalRecords: records.length 
        });
      } else {
        // Authentic CWR data structure with all 60+ fields from actual feed
        const demoData = [
          {
            "CWR Part Number": "010342",
            "Manufacturer Part Number": "MPN-010342",
            "UPC Code": "123456789012",
            "Quantity Available to Ship (Combined)": "150",
            "Quantity Available to Ship (NJ)": "75",
            "Quantity Available to Ship (FL)": "75",
            "Next Shipment Date (Combined)": "2025-07-01",
            "Next Shipment Date (NJ)": "2025-07-01",
            "Next Shipment Date (FL)": "2025-07-01",
            "Your Cost": "19.99",
            "List Price": "29.99",
            "M.A.P. Price": "24.99",
            "M.R.P. Price": "29.99",
            "Uppercase Title": "OIL FILTER - MERCURY MARINE",
            "Title": "Oil Filter - Mercury Marine",
            "Full Description": "High-performance oil filter for Mercury Marine engines with superior filtration technology",
            "Category ID": "FILTERS",
            "Category Name": "Oil Filters",
            "Manufacturer Name": "Mercury Marine",
            "Shipping Weight": "2.5",
            "Box Height": "4.5",
            "Box Length": "6.2",
            "Box Width": "4.5",
            "List of Accessories by SKU": "",
            "List of Accessories by MFG#": "",
            "Quick Specs": "Premium oil filter with advanced filtration",
            "Image (300x300) Url": "https://productimageserver.com/images/010342_300.jpg",
            "Image (1000x1000) Url": "https://productimageserver.com/images/010342_1000.jpg",
            "Non-stock": "No",
            "Drop Ships Direct From Vendor": "No",
            "Hazardous Materials": "No",
            "Truck Freight": "No",
            "Exportable": "Yes",
            "First Class Mail": "Yes",
            "Oversized": "No",
            "Remanufactured": "No",
            "Closeout": "No",
            "Harmonization Code": "8421.23.0000",
            "Country Of Origin": "USA",
            "Sale": "No",
            "Original Price (If on Sale/Closeout)": "",
            "Sale Start Date": "",
            "Sale End Date": "",
            "Rebate": "No",
            "Rebate Description": "",
            "Rebate Description With Link": "",
            "Rebate Start Date": "",
            "Rebate End Date": "",
            "Google Merchant Category": "Vehicle Parts & Accessories > Motor Vehicle Parts > Motor Vehicle Filters",
            "Quick Guide Literature (pdf) Url": "",
            "Owners Manual (pdf) Url": "",
            "Brochure Literature (pdf) Url": "",
            "Installation Guide (pdf) Url": "",
            "Video Urls": "",
            "Prop 65": "No",
            "Prop 65 Description": "",
            "Free Shipping": "Yes",
            "Free Shipping End Date": "",
            "Returnable": "Yes",
            "Image Additional (1000x1000) Urls": "",
            "Case Qty (NJ)": "12",
            "Case Qty (FL)": "12",
            "3rd Party Marketplaces": "Amazon, eBay",
            "FCC ID": ""
          }
        ];
        
        res.json({ 
          success: true, 
          data: demoData,
          totalRecords: demoData.length,
          note: "Using demo data - actual CSV not found"
        });
      }
      
    } catch (error) {
      console.error("Error fetching sample data:", error);
      res.status(500).json({ error: "Failed to fetch sample data" });
    }
  });

  // Basic health check endpoint
  app.get("/api/health", (req, res) => {
    res.json({ 
      status: "healthy", 
      timestamp: new Date().toISOString(),
      uptime: process.uptime()
    });
  });

  const httpServer = createServer(app);
  return httpServer;
}